# Generated by Django 5.0.1 on 2024-01-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djpj_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprogress",
            old_name="fairy_tale",
            new_name="fairytale",
        ),
        migrations.RenameField(
            model_name="userprogress",
            old_name="user",
            new_name="username",
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("username", "fairytale")},
        ),
    ]
