from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    #기초적인 함수
    path('userlogin', views.userlogin, name='userlogin'),
    path('usersignin', views.usersignin, name='usersignin'),
    path('logout_and_home/', views.logout_and_home, name='logout_and_home'),
    path('load_progress/', views.load_progress, name='load_progress'),
    path('saverobot/', views.saverobot, name='saverobot'),
    path('savepage/', views.savepage, name='savepage'),
    path('execute_code/', views.execute_code, name='execute_code'),
    path('get_completion/', views.get_completion, name='get_completion'),
    #동화 메인 홈
    path('', views.homepage, name='home'),
    path('fariytale/home', views.fairytale_home, name='fairytale_home'),
    #백설공주
    #백설공주 1
    path('fariytale/snowwhite/intro', views.snowwhite_home, name='snowwhite_home'),
    path('fariytale/snowwhite/01', views.snowwhite_01, name='snowwhite_01'),
    path('fariytale/snowwhite/02', views.snowwhite_02, name='snowwhite_02'),
    path('fariytale/snowwhite/03', views.snowwhite_03, name='snowwhite_03'),
    path('fariytale/snowwhite/04', views.snowwhite_04, name='snowwhite_04'),
    path('fariytale/snowwhite/05', views.snowwhite_05, name='snowwhite_05'),
    path('fariytale/snowwhite/06', views.snowwhite_06, name='snowwhite_06'),
    path('fariytale/snowwhite/07', views.snowwhite_07, name='snowwhite_07'),
    path('fariytale/snowwhite/08', views.snowwhite_08, name='snowwhite_08'),
    path('fariytale/snowwhite/09', views.snowwhite_09, name='snowwhite_09'),
    path('fariytale/snowwhite/10', views.snowwhite_10, name='snowwhite_10'),
    path('fariytale/snowwhite/11', views.snowwhite_11, name='snowwhite_11'),
    path('fariytale/snowwhite/12', views.snowwhite_12, name='snowwhite_12'),
    path('fariytale/snowwhite/13', views.snowwhite_13, name='snowwhite_13'),
    path('fariytale/snowwhite/14', views.snowwhite_14, name='snowwhite_14'),
    path('fariytale/snowwhite/15', views.snowwhite_15, name='snowwhite_15'),
    path('fariytale/snowwhite/16', views.snowwhite_16, name='snowwhite_16'),
    path('fariytale/snowwhite/17', views.snowwhite_17, name='snowwhite_17'),
    path('fariytale/snowwhite/18', views.snowwhite_18, name='snowwhite_18'),
    path('fariytale/snowwhite/19', views.snowwhite_19, name='snowwhite_19'),
    path('fariytale/snowwhite/20', views.snowwhite_20, name='snowwhite_20'),
    path('fariytale/snowwhite/21', views.snowwhite_21, name='snowwhite_21'),
    path('fariytale/snowwhite/22', views.snowwhite_22, name='snowwhite_22'),
    path('fariytale/snowwhite/23', views.snowwhite_23, name='snowwhite_23'),
    path('fariytale/snowwhite/24', views.snowwhite_24, name='snowwhite_24'),
    path('fariytale/snowwhite/25', views.snowwhite_25, name='snowwhite_25'),
    path('fariytale/snowwhite/26', views.snowwhite_26, name='snowwhite_26'),
    path('fariytale/snowwhite/test01', views.snowwhite_test01, name='snowwhite_test01'),
    path('fariytale/snowwhite/test02', views.snowwhite_test02, name='snowwhite_test02'),
    path('fariytale/snowwhite/test03', views.snowwhite_test03, name='snowwhite_test03'),
    path('fariytale/snowwhite/test04', views.snowwhite_test04, name='snowwhite_test04'),
    path('fariytale/snowwhite/test05', views.snowwhite_test05, name='snowwhite_test05'),
    #백설공주2
    path('fariytale/snowwhite2/intro', views.snowwhite2_intro, name='snowwhite2_intro'),
    path('fariytale/snowwhite2/01', views.snowwhite2_01, name='snowwhite2_01'),
    path('fariytale/snowwhite2/02', views.snowwhite2_02, name='snowwhite2_02'),
    path('fariytale/snowwhite2/03', views.snowwhite2_03, name='snowwhite2_03'),
    path('fariytale/snowwhite2/04', views.snowwhite2_04, name='snowwhite2_04'),
    path('fariytale/snowwhite2/05', views.snowwhite2_05, name='snowwhite2_05'),
    path('fariytale/snowwhite2/06', views.snowwhite2_06, name='snowwhite2_06'),
    path('fariytale/snowwhite2/07', views.snowwhite2_07, name='snowwhite2_07'),
    path('fariytale/snowwhite2/08', views.snowwhite2_08, name='snowwhite2_08'),
    path('fariytale/snowwhite2/09', views.snowwhite2_09, name='snowwhite2_09'),
    path('fariytale/snowwhite2/10', views.snowwhite2_10, name='snowwhite2_10'),
    path('fariytale/snowwhite2/11', views.snowwhite2_11, name='snowwhite2_11'),
    path('fariytale/snowwhite2/12', views.snowwhite2_12, name='snowwhite2_12'),
    path('fariytale/snowwhite2/13', views.snowwhite2_13, name='snowwhite2_13'),
    path('fariytale/snowwhite2/14', views.snowwhite2_14, name='snowwhite2_14'),
    path('fariytale/snowwhite2/15', views.snowwhite2_15, name='snowwhite2_15'),
    path('fariytale/snowwhite2/16', views.snowwhite2_16, name='snowwhite2_16'),
    path('fariytale/snowwhite2/17', views.snowwhite2_17, name='snowwhite2_17'),
    path('fariytale/snowwhite2/test01', views.snowwhite2_test01, name='snowwhite2_test01'),
    path('fariytale/snowwhite2/test02', views.snowwhite2_test02, name='snowwhite2_test02'),
    path('fariytale/snowwhite2/test03', views.snowwhite2_test03, name='snowwhite2_test03'),
    path('fariytale/snowwhite2/test04', views.snowwhite2_test04, name='snowwhite2_test04'),
    path('fariytale/snowwhite2/test05', views.snowwhite2_test05, name='snowwhite2_test05'),
    #백설공주3
    path('fariytale/snowwhite3/intro', views.snowwhite3_intro, name='snowwhite3_intro'),
    path('fariytale/snowwhite3/01', views.snowwhite3_01, name='snowwhite3_01'),
    path('fariytale/snowwhite3/02', views.snowwhite3_02, name='snowwhite3_02'),
    path('fariytale/snowwhite3/03', views.snowwhite3_03, name='snowwhite3_03'),
    path('fariytale/snowwhite3/04', views.snowwhite3_04, name='snowwhite3_04'),
    path('fariytale/snowwhite3/05', views.snowwhite3_05, name='snowwhite3_05'),
    path('fariytale/snowwhite3/06', views.snowwhite3_06, name='snowwhite3_06'),
    path('fariytale/snowwhite3/07', views.snowwhite3_07, name='snowwhite3_07'),
    path('fariytale/snowwhite3/08', views.snowwhite3_08, name='snowwhite3_08'),
    path('fariytale/snowwhite3/09', views.snowwhite3_09, name='snowwhite3_09'),
    path('fariytale/snowwhite3/10', views.snowwhite3_10, name='snowwhite3_10'),
    path('fariytale/snowwhite3/11', views.snowwhite3_11, name='snowwhite3_11'),
    path('fariytale/snowwhite3/12', views.snowwhite3_12, name='snowwhite3_12'),
    path('fariytale/snowwhite3/13', views.snowwhite3_13, name='snowwhite3_13'),
    path('fariytale/snowwhite3/test01', views.snowwhite3_test01, name='snowwhite3_test01'),
    path('fariytale/snowwhite3/test02', views.snowwhite3_test02, name='snowwhite3_test02'),
    path('fariytale/snowwhite3/test03', views.snowwhite3_test03, name='snowwhite3_test03'),
    #백설공주4
    path('fariytale/snowwhite4/intro', views.snowwhite4_intro, name='snowwhite4_intro'),
    path('fariytale/snowwhite4/01', views.snowwhite4_01, name='snowwhite4_01'),
    path('fariytale/snowwhite4/02', views.snowwhite4_02, name='snowwhite4_02'),
    path('fariytale/snowwhite4/03', views.snowwhite4_03, name='snowwhite4_03'),
    path('fariytale/snowwhite4/04', views.snowwhite4_04, name='snowwhite4_04'),
    path('fariytale/snowwhite4/05', views.snowwhite4_05, name='snowwhite4_05'),
    path('fariytale/snowwhite4/06', views.snowwhite4_06, name='snowwhite4_06'),
    path('fariytale/snowwhite4/07', views.snowwhite4_07, name='snowwhite4_07'),
    path('fariytale/snowwhite4/08', views.snowwhite4_08, name='snowwhite4_08'),
    path('fariytale/snowwhite4/09', views.snowwhite4_09, name='snowwhite4_09'),
    path('fariytale/snowwhite4/10', views.snowwhite4_10, name='snowwhite4_10'),
    path('fariytale/snowwhite4/11', views.snowwhite4_11, name='snowwhite4_11'),
    path('fariytale/snowwhite4/12', views.snowwhite4_12, name='snowwhite4_12'),
    path('fariytale/snowwhite4/test01', views.snowwhite4_test01, name='snowwhite4_test01'),
    path('fariytale/snowwhite4/test02', views.snowwhite4_test02, name='snowwhite4_test02'),
    #백설공주5
    path('fariytale/snowwhite5/intro', views.snowwhite5_intro, name='snowwhite5_intro'),
    path('fariytale/snowwhite5/01', views.snowwhite5_01, name='snowwhite5_01'),
    path('fariytale/snowwhite5/02', views.snowwhite5_02, name='snowwhite5_02'),
    path('fariytale/snowwhite5/03', views.snowwhite5_03, name='snowwhite5_03'),
    path('fariytale/snowwhite5/04', views.snowwhite5_04, name='snowwhite5_04'),
    path('fariytale/snowwhite5/05', views.snowwhite5_05, name='snowwhite5_05'),
    path('fariytale/snowwhite5/06', views.snowwhite5_06, name='snowwhite5_06'),
    path('fariytale/snowwhite5/07', views.snowwhite5_07, name='snowwhite5_07'),
    path('fariytale/snowwhite5/08', views.snowwhite5_08, name='snowwhite5_08'),
    path('fariytale/snowwhite5/09', views.snowwhite5_09, name='snowwhite5_09'),
    path('fariytale/snowwhite5/10', views.snowwhite5_10, name='snowwhite5_10'),
    path('fariytale/snowwhite5/11', views.snowwhite5_11, name='snowwhite5_11'),
    path('fariytale/snowwhite5/12', views.snowwhite5_12, name='snowwhite5_12'),
    path('fariytale/snowwhite5/13', views.snowwhite5_13, name='snowwhite5_13'),
    #테스트용경로
    path('fariytale/snowwhite/home/test', views.snowwhite_home_test, name='snowwhite_home_test'),
    path('fariytale/snowwhite/title/test', views.snowwhite_title_test, name='snowwhite_title_test'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)